language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t iyadprashant/reactnodenginxdocker -f Dockerfile.dev .

script:
  - docker run -e CI=true iyadprashant/reactnodenginxdocker npm run test
